Feature/vta 695
dvsa/cvs-auto-svc pull request #245
Opened 2022-07-05 08:20 UTC by IuliaDVSA

2022-07-19 15:10 UTC, blondeholly requested changes

2022-07-20 06:51 UTC, IuliaDVSA commented on src/main/java/clients/TestStationsClient.java
> +    private Response callGetTestStationsEmail(String p_umber) {
Yep, :) changed

2022-07-20 06:59 UTC, IuliaDVSA commented on src/test/java/atf/GetTestStations.java
> +        testStationSteps.validateEveryRecordHasFieldValue("testStationStatus", TestStationsData.buildTestStationData());
Removed, this should not have been here.

2022-07-20 07:00 UTC, IuliaDVSA commented on src/test/java/testresults/GetTestResults.java
> +@WithTag("In_test")
Removed

2022-07-20 07:00 UTC, IuliaDVSA commented on src/test/java/atf/GetTestStations.java
> +    @Title("CVSB-7949 - AC1 - API Consumer retrieve test stations reference data - testStationStatus : active or termination requested")
Removed

2022-07-20 07:00 UTC, IuliaDVSA commented on src/main/java/clients/TestStationsClient.java
> +                .get("/test-stations/{p_umber}");
Changed

2022-07-20 07:00 UTC, IuliaDVSA commented on src/main/java/clients/TestStationsClient.java
> +                .pathParam("p_umber", p_umber)
Changed

2022-07-20 07:02 UTC, IuliaDVSA commented on src/main/java/clients/TestStationsClient.java
> +//                .filters(new BasePathFilter())
Changed

2022-07-20 11:34 UTC, ZeypEr commented
VTA-695 has been approved and reviewed.

2022-07-20 11:36 UTC, ZeypEr approved these changes
VTA-695 has been approved and reviewed.

2022-07-26 06:40 UTC, blondeholly approved these changes

2022-07-26 09:37 UTC, merged

2022-07-26 09:37 UTC, IuliaDVSA commented
VTA-695 reviewed and merged