Feature/vta 696
dvsa/cvs-auto-svc pull request #247
Opened 2022-07-15 14:39 UTC by IuliaDVSA

2022-07-19 15:09 UTC, blondeholly requested changes

2022-07-20 07:39 UTC, IuliaDVSA commented on src/test/java/testtypes/GetTestTypesByIdNeg.java
> +@WithTag("In_test")
Removed

2022-07-20 11:37 UTC, ZeypEr approved these changes
VTA-696 has been approved and reviewed.

2022-07-26 06:41 UTC, blondeholly approved these changes

2022-07-26 09:39 UTC, merged

2022-07-26 09:39 UTC, IuliaDVSA commented
VTA-696 was reviewed and merged.